In [1]:
import pandas as pd
df= pd.read_csv(r"C:\Users\nk424\OneDrive\Scans\Desktop\training\Sample_Data\50_Startups.csv")
df.head()

Unnamed: 0  R&D Spend  Administration  Marketing Spend       State  \
0           0  165349.30       136897.90        471784.20    New York   
1           1  162597.80       151377.69        443898.63  California   
2           2  153441.61       101145.65        407934.64     Florida   
3           3  144372.51       118671.95        383199.72    New York   
4           4  142107.44        91391.87        366168.52     Florida   

      Profit  
0  192261.93  
1  191792.16  
2  191050.49  
3  182902.09  
4  166188.04

In [2]:
df.isnull().sum()

Unnamed: 0         0
R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0       50 non-null     int64  
 1   R&D Spend        50 non-null     float64
 2   Administration   50 non-null     float64
 3   Marketing Spend  50 non-null     float64
 4   State            50 non-null     object 
 5   Profit           50 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.5+ KB


In [4]:
order_label={"Florida":0,"California":1,"New York":2}

In [5]:
df["State_New"]=df["State"].map(order_label)

In [7]:
df.head()

Unnamed: 0  R&D Spend  Administration  Marketing Spend       State  \
0           0  165349.30       136897.90        471784.20    New York   
1           1  162597.80       151377.69        443898.63  California   
2           2  153441.61       101145.65        407934.64     Florida   
3           3  144372.51       118671.95        383199.72    New York   
4           4  142107.44        91391.87        366168.52     Florida   

      Profit  State_New  
0  192261.93          2  
1  191792.16          1  
2  191050.49          0  
3  182902.09          2  
4  166188.04          0

In [15]:
df.drop("State", axis=1, inplace=True)
df.head()

Unnamed: 0  R&D Spend  Administration  Marketing Spend     Profit  \
0           0  165349.30       136897.90        471784.20  192261.93   
1           1  162597.80       151377.69        443898.63  191792.16   
2           2  153441.61       101145.65        407934.64  191050.49   
3           3  144372.51       118671.95        383199.72  182902.09   
4           4  142107.44        91391.87        366168.52  166188.04   

   State_New  
0          2  
1          1  
2          0  
3          2  
4          0

In [16]:
x=df.drop("Profit",axis=1)
y=df['Profit']

In [17]:
x.head()

Unnamed: 0  R&D Spend  Administration  Marketing Spend  State_New
0           0  165349.30       136897.90        471784.20          2
1           1  162597.80       151377.69        443898.63          1
2           2  153441.61       101145.65        407934.64          0
3           3  144372.51       118671.95        383199.72          2
4           4  142107.44        91391.87        366168.52          0

In [18]:
y.head()

0    192261.93
1    191792.16
2    191050.49
3    182902.09
4    166188.04
Name: Profit, dtype: float64

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=50)


In [20]:
print("shape of x_train",x_train.shape)
print("shape of x_test",x_test.shape)

shape of x_train (40, 5)
shape of x_test (10, 5)


In [21]:
print("shape of y_train",y_train.shape)
print("shape of y_test",y_test.shape)

shape of y_train (40,)
shape of y_test (10,)


In [22]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
std.fit(x_train)
x_train=std.transform(x_train)
x_test=std.transform(x_test)

In [23]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [24]:
x_test[0,:]

array([ 0.62036611, -0.58762863,  1.3710944 ,  0.04004591,  0.09166985])

In [26]:
y_test

34     96712.90
36     90708.29
1     191792.16
38     81229.16
8     152211.87
16    126993.03
35     96479.61
13    134307.45
29    101004.74
24    108552.14
Name: Profit, dtype: float64

In [25]:
lr.predict([x_test[0,:]])

array([84393.48677044])

In [27]:
lr.predict([x_test[1,:]])

array([75246.56987141])

In [28]:
lr.predict([x_test[2,:]])

array([181758.20925713])

In [30]:
y_pred=lr.predict(x_test)

In [31]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(r2_score(y_test,y_pred))

0.9300130409764846


In [32]:
print(mean_absolute_error(y_test,y_pred))

6834.921785255508


In [33]:
print(mean_squared_error(y_test,y_pred))

72463400.50375085


In [34]:
import numpy as np
print(np.sqrt(mean_squared_error(y_test,y_pred)))

8512.543715232883
